compile:
	g++ -std=c++17 sol.cpp -static -Wall -Wshadow -Wno-unused-result -O2 -o sol
compileAndRun:
	g++ -std=c++17 sol.cpp -static -Wall -Wno-unused-result -O2 -o sol && ./sol < in
runWithInput:
	./sol < in
