set splitright
set shiftwidth=2
set tabstop=2
set autoindent
set expandtab

command! Terminal :vert terminal ++cols=60
autocmd VimEnter *.cpp Terminal

noremap <F5> :w <CR> <C-w>l clear <CR> make compile <CR>
noremap <F6> :w <CR> <C-w>l clear <CR> make compileAndRun <CR>
tnoremap <F7> <CR> make runWithInput <CR>

nmap <C-h> <C-w>h
nmap <C-l> <C-w>l

tnoremap <C-h> <C-w>h
tnoremap <C-l> <C-w>l

noremap QQ :qall! <CR>
tnoremap QQ <C-w>N:qall!<CR>
